#!/bin/bash

find_ssh_key() {
  dir="$HOME/.ssh/keys/$1"
  key=$(cat $dir 2> /dev/null)
  if [ $? -ne 0 ]; then
    echo "Failed. Could not find file with key name '$1' in $HOME/.ssh/keys"
    exit 1
  fi

  echo $key
}

approve() {
  if [ "$1" == "" ]; then
    echo "I need a key name to approve"
    exit 1
  fi
  ls ~/.ssh/keys | grep "$1"
  if [ $? -ne 0 ]; then
    echo "~/.ssh/keys/$1 does not exist, so I couldn't approve $1, giving up"
    exit 1
  fi
  key=$(find_ssh_key $1)
  grep -qxF "$key" ~/.ssh/authorized_keys
  if [ $? -eq 0 ]; then
    echo "$1 is already approved"
  else
    echo $key >> $HOME/.ssh/authorized_keys
    echo "approved $1 for SSH access"
  fi
}

revoke() {
  key=$(find_ssh_key $1)
  grep -qxF "$key" ~/.ssh/authorized_keys
  if [ $? -eq 0 ]; then
    escaped_key="${key//\//\\/}"
    sed -i "/$escaped_key/d" $HOME/.ssh/authorized_keys
    echo "revoked $1's SSH access"
  else
    echo "$1's SSH access is already revoked"
  fi
}

approve_all() {
  for key in $(ls ~/.ssh/keys/)
  do
    approve $key
  done
}

revoke_all() {
  for key in $(ls ~/.ssh/keys/)
  do
    revoke $key
  done
}

if [ "$1" == "approve" ] && [ "$2" == "all" ]; then
  approve_all
elif [ "$1" == "approve" ]; then
  approve $2
elif [ "$1" == "revoke" ] && [ "$2" == "all" ]; then
  revoke_all
elif [ "$1" == "revoke" ]; then
  revoke $2
else
  echo "usage: ssh_access [revoke | approve] [all | ssh_key_file_name]"
  exit 1
fi
