#!/bin/bash

sudo echo "a prompt for sudo" >/dev/null

uninstall_mac() {
  sudo rm /usr/local/bin/mob
  sudo rm /usr/local/bin/ssh_access
}

install_linux() {
  rm ~/.local/bin/mob
  rm ~/.local/bin/ssh_access
  sudo rm /usr/share/bash-completion/completions/ssh_access
}


case $OSTYPE in
  'darwin20')
    uninstall_mac
    ;;
  *)
    uninstall_linux
    ;;
esac

